FROM node:10.16-alpine as build

WORKDIR /usr/app

COPY ./package.json ./
RUN yarn install

COPY . .

CMD ["yarn", "build"]

FROM nginx
EXPOSE 3012
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/app/build /usr/share/nginx/html