version: '2'
services:
  proxy:
    image: haproxy:2.1
    command: "haproxy -f /haproxy/haproxy-dev.cfg"
    container_name: magpay-proxy
    ports:
      - "3050:3050"
    volumes:
      - ./etc/haproxy/:/haproxy
    depends_on:
      - client
      - api
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: magpay-client
    volumes:
      - /usr/app/node_modules/
      - ./client:/usr/app
    ports:
      - "3012:3012"
    environment:
      - PORT=3012
    depends_on:
      - api
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    container_name: magpay-api
    volumes:
      - /usr/app/node_modules/
      - ./api:/usr/app
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - CLIENT_ID=28209513233-ndt4p5trvkqaqjooc7hg5q4u0na2ndf0.apps.googleusercontent.com
      - CLIENT_SECRET=UoJDSlQwLQFPHMxxOesIByzK
      - REDIRECT_URI=http://localhost:3050/api/oauthcallback
      - DOMAIN=http://localhost:3050
